import type { ReturnTrip } from './types';

export const mockReturnTrips: ReturnTrip[] = [
  {
    id: 181,
    driverId: 242,
    driverRating: '4.6',
    driverCarType: 'Sedan',
    pickupCity: 'Chennai',
    destinationCity: 'Tiruvallur',
    pickupFormatAddress: {
      formattedAddress: 'Kamaraj Ave 2nd St, Chennai',
      name: 'Kamaraj Ave 2nd St, Chennai',
    },
    dropFormatAddress: {
      formattedAddress: 'Veraragave Street, Kakkalur',
      name: 'Veraragave Street, Kakkalur',
    },
    cabSnapshot: {
      id: 118,
      carType: 'Sedan',
      carNumber: 'TN09AB4721',
      vehicleType: 'Toyota Etios',
      modelYear: 2026,
    },
    finalPrice: 492,
    discountAmount: 211,
    expiresAt: new Date(Date.now() + 72 * 60 * 60 * 1000).toISOString(),
    status: 'ACTIVE',
    minutesToExpiry: 132,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    zone: 'Chennai',
    Driver: {
      id: 242,
      firstName: 'Kokki Kumar Kalash',
      lastName: null,
      phoneNumber: '+919900000016',
      rating: '4.6',
      carType: 'Sedan',
      cabId: 118,
    },
  },
  {
    id: 176,
    driverId: 151,
    driverRating: '3.7',
    driverCarType: 'Mini',
    pickupCity: 'Chennai',
    destinationCity: 'Vellore',
    pickupFormatAddress: {
      formattedAddress: 'Tower-C, Elcot Sez, Sholinganallur, Chennai',
      name: 'Tower-C, Elcot Sez, Sholinganallur, Chennai',
    },
    dropFormatAddress: {
      formattedAddress: 'Vellore, Tamil Nadu, India',
      name: 'Vellore, Tamil Nadu, India',
    },
    cabSnapshot: {
      id: 118,
      carType: 'Mini',
      carNumber: 'TN09AB4721',
      vehicleType: 'Toyota Etios',
      modelYear: 2024,
    },
    finalPrice: 558,
    discountAmount: 120,
    expiresAt: new Date(Date.now() + 18 * 60 * 60 * 1000).toISOString(),
    status: 'ACTIVE',
    minutesToExpiry: 55,
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    zone: 'Chennai',
    Driver: {
      id: 151,
      firstName: 'Mowfica Rides',
      lastName: null,
      phoneNumber: '+919047562628',
      rating: '3.7',
      carType: 'Mini',
      cabId: 118,
    },
  },
  {
    id: 149,
    driverId: 88,
    driverRating: '4.2',
    driverCarType: 'SUV',
    pickupCity: 'Chennai',
    destinationCity: 'Kanchipuram',
    pickupFormatAddress: {
      formattedAddress: 'Guindy, Chennai',
      name: 'Guindy, Chennai',
    },
    dropFormatAddress: {
      formattedAddress: 'Kanchipuram, Tamil Nadu, India',
      name: 'Kanchipuram, Tamil Nadu, India',
    },
    cabSnapshot: {
      id: 77,
      carType: 'SUV',
      carNumber: 'TN11CD7788',
      vehicleType: 'Innova',
      modelYear: 2025,
    },
    finalPrice: 1200,
    discountAmount: 180,
    expiresAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    status: 'EXPIRED',
    minutesToExpiry: 0,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    zone: 'Chennai',
    Driver: {
      id: 88,
      firstName: 'Arunaja Sit Testing',
      lastName: null,
      phoneNumber: '+917070707070',
      rating: '4.2',
      carType: 'SUV',
      cabId: 77,
    },
  },
];
